// Mock data for development when database is not available
export const MOCK_POIS = [
  {
    id: "1",
    name: "Startup Campus Lisbon",
    description: "Modern coworking space with high-speed internet and coffee",
    latitude: 38.7223,
    longitude: -9.1393,
    category: "coworking",
    rating: 4.5,
    tags: ["wifi", "coffee", "meetings"],
    metadata: {
      hours: "9:00-18:00",
      cost: "€25/day",
      wifi: "excellent",
    },
    region: "lisbon",
    views_count: 150,
    favorites_count: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      display_name: "Admin",
      avatar_url: null,
    },
  },
  {
    id: "2", 
    name: "Café Central",
    description: "Traditional Portuguese café with authentic pastries",
    latitude: 38.7150,
    longitude: -9.1400,
    category: "cafe",
    rating: 4.2,
    tags: ["coffee", "pastries", "traditional"],
    metadata: {
      hours: "7:00-20:00",
      cost: "€3-8",
      wifi: "good",
    },
    region: "lisbon",
    views_count: 89,
    favorites_count: 23,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      display_name: "Local Guide",
      avatar_url: null,
    },
  },
  {
    id: "3",
    name: "Nomad Hub Seville", 
    description: "Digital nomad coworking space in historic Andalusia",
    latitude: 37.3891,
    longitude: -5.9845,
    category: "coworking",
    rating: 4.7,
    tags: ["coworking", "nomads", "historic"],
    metadata: {
      hours: "24/7",
      cost: "€30/day",
      wifi: "excellent",
    },
    region: "andalusia",
    views_count: 203,
    favorites_count: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      display_name: "Community Manager",
      avatar_url: null,
    },
  },
];